font_family FiraCode Nerd Font Mono
bold_font auto
italic_font Iosevka Nerd Font
bold_italic_font Iosevka Nerd Font


linux_display_server wayland
shell_integration no-cursor

confirm_os_window_close 0
enable_audio_bell no
mouse_hide_wait -1.0

cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval -1

enabled_layouts Tall, *

background_opacity 0.97

window_margin_width 0

inactive_tab_font_style bold
active_tab_font_style bold
tab_bar_margin_width 0
tab_bar_style powerline
tab_fade 1
tab_powerline_style slanted



action_alias launch_tab launch --cwd=current --type=tab
action_alias launch_window launch --cwd=current --type=window

map kitty_mod+enter launch_window
map kitty_mod+t launch_tab


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
